version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  api:
    build: ./backend
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=zeek-logs
      - DATABASE_URL=sqlite:///events.db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  honeypot-runner:
    build: ./honeypot
    volumes:
      - honeypot-logs:/var/log/honeypot

volumes:
  honeypot-logs:
